### ISSUE TITLE
Error on Valuation Determiner when entering more than 3 chars

### ISSUE THREAD

**Issue by 0xMimir** [devfinwiz/Fin-Maestro#37] opened 2023-06-28 14:36 UTC
[Screencast from 06-28-2023 04:32:19 PM.webm](https://github.com/devfinwiz/Fin-Maestro/assets/108837858/df942446-6df5-4253-a24c-388c701c604a)

On branch [docker](https://github.com/devfinwiz/Fin-Maestro/tree/docker) after building the project and going on frontend, when trying to type more than 3 chars input locks up, this only happens Valuation Determiner tab, it doesn't happen on any other

**Comment by yash-dk** [comment] 2023-06-30 08:43
Will need to repro it. I think it is due to the recommendation of stocks but will need to check.

**Comment by devfinwiz** [comment] 2023-09-11 17:47
Unable to reproduce this issue. The input field stays just fine. 
Kindly try the manual approach too if you haven't yet or try setting up a new environment before trying to deploy it again. 

Closing this issue for now.

**Closed** 2023-09-11 17:47 UTC
Labels: needs-triage
